//@ui5-bundle nl/gasunie/workzone/library/library-preload.js
sap.ui.predefine("nl/gasunie/workzone/library/controls/Example",["./../library","sap/ui/core/Control","./ExampleRenderer"],function(e,r,n){"use strict";var a=r.extend("nl.gasunie.workzone.library.controls.Example",{metadata:{library:"nl.gasunie.workzone.library",properties:{text:{type:"string",defaultValue:null}},events:{press:{}}},renderer:n});return a},true);
sap.ui.predefine("nl/gasunie/workzone/library/controls/ExampleRenderer",[],function(){"use strict";var e={};e.render=function(e,r){e.write("<div");e.writeControlData(r);e.addClass("sapRULTExample");e.writeClasses();e.write(">");e.write(sap.ui.getCore().getLibraryResourceBundle("nl.gasunie.workzone.library").getText("ANY_TEXT"));e.writeEscaped(r.getText());e.write("</div>")};return e},true);
sap.ui.predefine("nl/gasunie/workzone/library/library",["sap/ui/core/library"],function(){"use strict";sap.ui.getCore().initLibrary({name:"nl.gasunie.workzone.library",version:"1.0.0",dependencies:["sap.ui.core"],noLibraryCSS:true,types:[],interfaces:[],controls:["nl.gasunie.workzone.library.controls.Example"],elements:[]});const e=nl.gasunie.workzone.library;e.getHelloWorld=()=>"Hello world part IV";return e},false);
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"nl/gasunie/workzone/library/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"nl.gasunie.workzone.library","type":"library","applicationVersion":{"version":"1.0.0"},"title":"Demo Lib","description":"Demo Lib","ach":"","offline":true},"sap.cloud":{"public":true,"service":"nl.gasunie.workzone.library"},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"dependencies":{"minUI5Version":"1.52.0","libs":{"sap.ui.core":{"minUI5Version":"1.52.0"}}},"library":{"i18n":"messagebundle.properties","css":true,"content":{"controls":["nl.gasunie.workzone.library.Example"],"elements":[],"types":[],"interfaces":[]}}}}'
}});
